AC_INIT
AC_CANONICAL_SYSTEM
AM_INIT_AUTOMAKE(taocrypt,0.9.0) 
AM_CONFIG_HEADER(include/config.h)

# make sure configure doesn't add to CXXFLAGS
CXXFLAGS="$CXXFLAGS $C_EXTRA_FLAGS"    

AC_PROG_CXX
AC_PROG_INSTALL
AC_PROG_RANLIB


AC_C_BIGENDIAN

AC_CHECK_SIZEOF(long, 4)
AC_CHECK_SIZEOF(long long, 8)
if test "$ac_cv_sizeof_long_long" -eq 0
then
  AC_MSG_ERROR("TaoCrypt needs a long long type.")
fi


OPTIMIZE_CXXFLAGS="-O3"
DEBUG_CXXFLAGS="-g"


AC_ARG_ENABLE(debug,
    [  --enable-debug          Enable TaoCrypt debugging support (default: enabled)],
    [ ENABLED_DEBUG=$enableval ],
    [ ENABLED_DEBUG=yes ]
    )
if test "$ENABLED_DEBUG" = "yes"
then
  # Full debug. Very slow in some cases
  CXXFLAGS="$DEBUG_CXXFLAGS $CXXFLAGS"
else
  # Optimized version. No debug
  CXXFLAGS="$OPTIMIZE_CXXFLAGS $CXXFLAGS -DNDEBUG"
fi


if test "$GCC" = "yes"
then
    CXXFLAGS="$CXXFLAGS -fno-exceptions -fno-rtti"
    if test "$target_vendor" = "pc" && test "$ENABLED_DEBUG" == "no"
    then
        CXXFLAGS="$CXXFLAGS -march=$target_cpu"
    fi
fi


AC_ARG_ENABLE(kernel-mode,
    [  --enable-kernel-mode    Enable TaoCrypt for Kernel Module (default: disabled)],
    [ ENABLED_KERNEL_MODE=$enableval ],
    [ ENABLED_KERNEL_MODE=no ]
    )

if test "$ENABLED_KERNEL_MODE" = "yes"
then
    CXXFLAGS="$CXXFLAGS -DTAOCRYPT_KERNEL_MODE"
fi


AC_ARG_ENABLE(pure-c,
    [  --enable-pure-c         Enable a Pure C build, see docs (default: disabled)],
    [ ENABLED_PURE_C=$enableval ],
    [ ENABLED_PURE_C=no ]
    )

if test "$ENABLED_PURE_C" = "yes"
then
    CXXFLAGS="$CXXFLAGS -DYASSL_PURE_C"
fi


AC_ARG_ENABLE(ia32-asm,
    [  --enable-ia32-asm       Enable TaoCrypt ia32 assembly (default: enabled)],
    [ ENABLED_IA32ASM=$enableval ],
    [ ENABLED_IA32ASM=yes ]
    )

if test "$ENABLED_IA32ASM" = "no"
then
    CXXFLAGS="$CXXFLAGS -DDISABLE_TAO_ASM"
fi

AC_SUBST(CXXFLAGS)



AC_CONFIG_FILES(Makefile dnl
        src/Makefile dnl
        test/Makefile dnl
        benchmark/Makefile) 

AC_OUTPUT
